id: dogs-vs-cats-redux-kernels-edition
name: "Dogs vs. Cats Redux: Kernels Edition"
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dogs-vs-cats-redux-kernels-edition/description.md

dataset:
  answers: dogs-vs-cats-redux-kernels-edition/prepared/private/answers.csv
  lite_answers: dogs-vs-cats-redux-kernels-edition/prepared_lite/private/answers.csv
  sample_submission: dogs-vs-cats-redux-kernels-edition/prepared/public/sample_submission.csv

grader:
  name: log-loss
  grade_fn: mlebench.competitions.dogs-vs-cats-redux-kernels-edition.grade:grade

lite_grader:
  name: log-loss
  grade_fn: mlebench.competitions.dogs-vs-cats-redux-kernels-edition.grade:grade_lite

preparer: mlebench.competitions.dogs-vs-cats-redux-kernels-edition.prepare:prepare
lite_preparer: mlebench.competitions.dogs-vs-cats-redux-kernels-edition.prepare:prepare_lite
