id: spooky-author-identification
name: Spooky Author Identification
competition_type: simple
awards_medals: false
prizes: null
description: mlebench/competitions/spooky-author-identification/description.md

dataset:
  answers: spooky-author-identification/prepared/private/answers.csv
  lite_answers: spooky-author-identification/prepared_lite/private/answers.csv
  sample_submission: spooky-author-identification/prepared/public/sample_submission.csv

grader:
  name: multi-class-log-loss
  grade_fn: mlebench.competitions.spooky-author-identification.grade:grade

lite_grader:
  name: multi-class-log-loss
  grade_fn: mlebench.competitions.spooky-author-identification.grade:grade

preparer: mlebench.competitions.spooky-author-identification.prepare:prepare
lite_preparer: mlebench.competitions.spooky-author-identification.prepare:prepare_lite
