id: tabular-playground-series-dec-2021
name: Tabular Playground Series - Dec 2021
competition_type: simple
awards_medals: false
prizes: null
description: mlebench/competitions/tabular-playground-series-dec-2021/description.md

dataset:
  answers: tabular-playground-series-dec-2021/prepared/private/answers.csv
  lite_answers: tabular-playground-series-dec-2021/prepared_lite/private/answers.csv
  sample_submission: tabular-playground-series-dec-2021/prepared/public/sample_submission.csv

grader:
  name: multi-class-classification-accuracy
  grade_fn: mlebench.competitions.tabular-playground-series-dec-2021.grade:grade

lite_grader:
  name: multi-class-classification-accuracy
  grade_fn: mlebench.competitions.tabular-playground-series-dec-2021.grade:grade_lite

preparer: mlebench.competitions.tabular-playground-series-dec-2021.prepare:prepare
lite_preparer: mlebench.competitions.tabular-playground-series-dec-2021.prepare:prepare_lite
