id: text-normalization-challenge-russian-language
name: Text Normalization Challenge - Russian Language
competition_type: simple
awards_medals: true
prizes:
  - position: 1
    value: 12000
  - position: 2
    value: 8000
  - position: 3
    value: 5000
description: mlebench/competitions/text-normalization-challenge-russian-language/description.md

dataset:
  answers: text-normalization-challenge-russian-language/prepared/private/answers.csv
  lite_answers: text-normalization-challenge-russian-language/prepared_lite/private/answers.csv
  sample_submission: text-normalization-challenge-russian-language/prepared/private/sample_submission.csv

grader:
  name: accuracy
  grade_fn: mlebench.competitions.text-normalization-challenge-russian-language.grade:grade

lite_grader:
  name: accuracy
  grade_fn: mlebench.competitions.text-normalization-challenge-russian-language.grade:grade
  
preparer: mlebench.competitions.text-normalization-challenge-russian-language.prepare:prepare
lite_preparer: mlebench.competitions.text-normalization-challenge-russian-language.prepare:prepare_lite
