id: histopathologic-cancer-detection
name: Histopathologic Cancer Detection
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/histopathologic-cancer-detection/description.md

dataset:
  answers: histopathologic-cancer-detection/prepared/private/answers.csv
  lite_answers: histopathologic-cancer-detection/prepared_lite/private/answers.csv
  sample_submission: histopathologic-cancer-detection/prepared/public/sample_submission.csv

grader:
  name: auc-roc
  grade_fn: mlebench.competitions.histopathologic-cancer-detection.grade:grade

lite_grader:
  name: auc-roc
  grade_fn: mlebench.competitions.histopathologic-cancer-detection.grade:grade_lite

preparer: mlebench.competitions.histopathologic-cancer-detection.prepare:prepare
lite_preparer: mlebench.competitions.histopathologic-cancer-detection.prepare:prepare_lite
